title: Catbug's Blog
description: "A blog about cognitive science, machine learning, and data science"
author:
  name: "Catbug"
  email: "pablo.caceres.maldonado@gmail.com"
  url: "http://pabloinsente.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Catbug"
year : "2020"
